spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: "http://localhost:8080/realms/ms_keycloak"
    application:
        name: gateway-service
    config:
        import: optional:configserver:http://localhost:8888
jwt:
    auth:
        converter:
            resource-id: ms_keycloak_client
            principle-attribute: preferred_username