spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/ms-keycloak"
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
jwt:
  auth:
    converter:
      resource-id: ms-keycloack
      principle-attribute: preferred_username