server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cart
      username: silver
      password: silver
      authentication-database: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka