server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cart-service
          uri: lb:http://CART-SERVICE
          predicates:
            - Path=/api/v1/carts/**
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
            - Path=/api/v1/product/**